# Generated by Django 5.0.4 on 2024-04-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=45)),
                ('Last_name', models.CharField(max_length=45)),
                ('addressMail', models.EmailField(max_length=45)),
                ('Matricule', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=45)),
                ('Last_name', models.CharField(max_length=45)),
                ('addressMail', models.EmailField(max_length=45)),
                ('Matricule', models.IntegerField()),
            ],
        ),
    ]
